version: '3'

services:
  vehiclemonitoring.services.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vehiclemonitoring.gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vehiclemonitoring.statusservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vehiclemonitoring.ui.webportal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  vehiclemonitoring.customersvc.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat




